name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    - name: Show secret and variable
      run: |
        echo "Variable: ${{ vars.MY_VAR }}"
        echo "Secret is set (hidden)"
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}

    - name: Create test results file
      run: echo "All tests passed on Python ${{ matrix.python-version }}" > test-results-${{ matrix.python-version }}.txt

    - name: Upload test results artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.python-version }}
        path: test-results-${{ matrix.python-version }}.txt

    - name: Simulate Deployment
      run: echo "Deploying application tested on Python ${{ matrix.python-version }} to production..."
